apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.fullname" . }}-nodeport
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    {{- include "orchestrator.selectorLabels" . | nindent 4 }}