# Secret Scanning Custom Patterns
# This file defines custom patterns for secret scanning specific to 5dlabs

patterns:
  - name: 5dlabs API Key
    pattern: |
      5dlabs[_-]?api[_-]?key[_-]?[0-9a-zA-Z]{32,}

  - name: Internal Service Token
    pattern: |
      (srv|service)[_-]?token[_-]?[0-9a-f]{40,}

  - name: Anthropic API Key (Custom)
    pattern: |
      sk-ant-[a-zA-Z0-9]{93}

  - name: Twingate Service Key
    pattern: |
      twingate[_-]?service[_-]?key.*[0-9a-zA-Z+/=]{100,}

# Paths to exclude from scanning (if needed)
paths-ignore:
  - "**/*.md"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"