apiVersion: orchestrator.io/v1
kind: TaskRun
metadata:
  name: test-taskrun-ci
  namespace: test-platform
spec:
  taskId: 9999
  serviceName: "test-service"
  agentName: "test-agent"
  contextVersion: 1
  markdownFiles:
    - filename: "task.md"
      content: |
        # Test Task for CI
        This is a test task for integration testing.
        
        ## Description
        Verify that TaskRun CRD works correctly in CI environment.
        
        ## Acceptance Criteria
        - TaskRun resource can be created
        - Status is updated correctly
        - ConfigMap is created with task files
      fileType: "task"
    - filename: "design-spec.md"
      content: |
        # Test Design Specification
        Simple test service for CI validation.
      fileType: "design-spec"
    - filename: "prompt.md"
      content: |
        # Test Prompt
        This is a test prompt for CI validation only.
      fileType: "prompt"