apiVersion: v1
kind: Pod
metadata:
  name: test-volume
  namespace: telemetry
spec:
  nodeSelector:
    kubernetes.io/hostname: talos-a43-ee1  # Force to worker node
  containers:
  - name: test
    image: busybox
    command: ["sh", "-c", "ls -la /var/mnt/ && sleep 3600"]
    volumeMounts:
    - name: host-var
      mountPath: /var/mnt
      readOnly: true
  volumes:
  - name: host-var
    hostPath:
      path: /var/mnt
      type: Directory