apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: platform-runner-deployment
  namespace: arc-systems
spec:
  replicas: 2
  template:
    spec:
      repository: 5dlabs/platform

      # GitHub authentication
      githubAPICredentialsFrom:
        secretRef:
          name: arc-github-token

      labels:
        - self-hosted
        - linux
        - x64
        - k8s-runner

      # Runner container resources
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"

      # Use runner image with Docker-in-Docker support
      image: summerwind/actions-runner-dind:latest
      
      # Docker in Docker configuration
      dockerEnabled: true
      dockerdWithinRunnerContainer: true

      # Environment variables
      env:
        # Option 1: Disable ephemeral mode for more stable runners
        # - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        #   value: "false"
        
        # Option 2: Keep ephemeral but be aware of the behavior
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
          
        # Fix PATH by using runner's startup script
        - name: ACTIONS_RUNNER_HOOK_JOB_STARTED
          value: |
            #!/bin/bash
            echo "export PATH=/shared:$PATH" >> $GITHUB_ENV

      # Service account with necessary permissions
      serviceAccountName: github-runner

      # Init container to install tools
      initContainers:
        - name: install-tools
          image: alpine:3.19
          command:
            - sh
            - -c
            - |
              echo "Installing tools..."
              apk add --no-cache wget tar
              
              echo "Installing kubectl..."
              wget -q -O /shared/kubectl https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
              chmod +x /shared/kubectl
              
              echo "Installing helm..."
              wget -q -O /tmp/helm.tar.gz https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz
              tar -xzf /tmp/helm.tar.gz -C /tmp
              mv /tmp/linux-amd64/helm /shared/helm
              chmod +x /shared/helm
              
              # Create symlinks in a standard location
              mkdir -p /shared/bin
              ln -sf /shared/kubectl /shared/bin/kubectl
              ln -sf /shared/helm /shared/bin/helm
              
              echo "Tools installed successfully"
              ls -la /shared/
              /shared/kubectl version --client || echo "kubectl test failed"
              /shared/helm version || echo "helm test failed"
          volumeMounts:
            - name: shared-tools
              mountPath: /shared

      # Volume for sharing tools
      volumes:
        - name: shared-tools
          emptyDir: {}
      
      # Volume mounts for main container
      volumeMounts:
        - name: shared-tools
          mountPath: /shared
          
      # Add startup script to set PATH
      dockerVolumeMounts:
        - name: shared-tools
          mountPath: /shared

      # Security context
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000