apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runner-orchestrator
  namespace: orchestrator
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-orchestrator
  namespace: orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-runner-orchestrator
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: arc-systems