apiVersion: batch/v1
kind: Job
metadata:
  name: create-storage-dirs
  namespace: telemetry
spec:
  template:
    metadata:
      labels:
        app: create-dirs
    spec:
      nodeSelector:
        kubernetes.io/hostname: talos-a43-ee1
      restartPolicy: Never
      containers:
      - name: create-dirs
        image: busybox
        command: 
        - sh
        - -c
        - |
          mkdir -p /host/var/telemetry-storage/victoria-metrics
          mkdir -p /host/var/telemetry-storage/victoria-logs
          mkdir -p /host/var/telemetry-storage/grafana
          mkdir -p /host/var/telemetry-storage/claude-code-workspace
          chmod -R 777 /host/var/telemetry-storage
          ls -la /host/var/telemetry-storage/
        volumeMounts:
        - name: host-var
          mountPath: /host/var
        securityContext:
          privileged: true
      volumes:
      - name: host-var
        hostPath:
          path: /var
          type: Directory