name: Build Rust Builder Image

on:
  push:
    branches: [ 'feature/example-project-and-cli' ]
    paths:
      - 'infra/images/rust-builder/**'
      - '.github/workflows/build-rust-image.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/rust-builder

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Enable advanced caching features
          driver-opts: |
            image=moby/buildkit:latest

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./infra/images/rust-builder/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enhanced caching strategy
          cache-from: |
            type=gha,scope=rust-builder
            type=gha,scope=rust-builder-${{ github.ref_name }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: |
            type=gha,scope=rust-builder-${{ github.ref_name }},mode=max
            type=gha,scope=rust-builder,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            # Build-time optimizations
            CARGO_INCREMENTAL=0
            CARGO_NET_RETRY=10
            RUST_BACKTRACE=1

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}

      - name: Cache summary
        run: |
          echo "## Docker Build Cache Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **GitHub Actions Cache**: Enabled with branch-specific scoping" >> $GITHUB_STEP_SUMMARY
          echo "- **Registry Cache**: Fallback cache stored in container registry" >> $GITHUB_STEP_SUMMARY
          echo "- **Cache Scopes**: \`rust-builder\` (global), \`rust-builder-${{ github.ref_name }}\` (branch)" >> $GITHUB_STEP_SUMMARY
          echo "- **Built Image**: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The pre-warmed dependencies are now baked into the image and will be used by CI/CD workflows." >> $GITHUB_STEP_SUMMARY
