name: Build Rust Builder Image

on:
  push:
    branches: [ 'main', 'feature/example-project-and-cli' ]
    tags: [ 'v*' ]
    paths:
      - 'infra/images/rust-builder/**'
      - '.github/workflows/build-rust-image.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/rust-builder

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Enable advanced caching features
          driver-opts: |
            image=moby/buildkit:latest

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # For version tags (v1.0.0), create versioned image
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            # For main branch, tag as 'main' and 'latest'
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=main,enable={{is_default_branch}}
            # For feature branches, use branch name
            type=ref,event=branch
            # For PRs
            type=ref,event=pr
            # Include SHA for traceability
            type=sha,prefix={{branch}}-,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./infra/images/rust-builder/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enhanced caching strategy
          cache-from: |
            type=gha,scope=rust-builder
            type=gha,scope=rust-builder-${{ github.ref_name }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: |
            type=gha,scope=rust-builder-${{ github.ref_name }},mode=max
            type=gha,scope=rust-builder,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            # Build-time optimizations
            CARGO_INCREMENTAL=0
            CARGO_NET_RETRY=10
            RUST_BACKTRACE=1

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}

      - name: Cache summary
        run: |
          echo "## Docker Build Cache Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **GitHub Actions Cache**: Enabled with branch-specific scoping" >> $GITHUB_STEP_SUMMARY
          echo "- **Registry Cache**: Fallback cache stored in container registry" >> $GITHUB_STEP_SUMMARY
          echo "- **Cache Scopes**: \`rust-builder\` (global), \`rust-builder-${{ github.ref_name }}\` (branch)" >> $GITHUB_STEP_SUMMARY
          echo "- **Built Image**: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The pre-warmed dependencies are now baked into the image and will be used by CI/CD workflows." >> $GITHUB_STEP_SUMMARY

  # Cycle Arc runners to use new image
  cycle-runners:
    needs: build-and-push
    runs-on: [self-hosted, k8s-runner]  # Run on existing k8s-runner that has kubectl/twingate
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/example-project-and-cli'
    steps:
      - name: Cycle rust-builder runners
        run: |
          echo "🔄 Rolling restart of Arc runners to use new rust-builder image..."
          
          # Note: The runnerdeployment should use imagePullPolicy: Always
          # and the 'latest' tag to automatically get new images
          
          # Delete pods to force recreation with new image
          kubectl delete pods -n arc-systems \
            -l runner-deployment-name=agent-platform-runner-deployment \
            --grace-period=30 || echo "No runner pods found"
          
          echo "✅ Runners will restart and pull the latest rust-builder image"
          echo "Note: It may take 1-2 minutes for all runners to be ready"
          echo ""
          echo "⚠️  Make sure the runnerdeployment uses:"
          echo "   - imagePullPolicy: Always"
          echo "   - A tag that gets updated (e.g., 'latest' or branch tag)"
