name: Cycle Rust Builder Runners

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for cycling runners'
        required: false
        default: 'Manual restart requested'

jobs:
  cycle-runners:
    runs-on: [self-hosted, k8s-runner]
    steps:
      - name: Cycle rust-builder runners
        run: |
          echo "🔄 Cycling rust-builder runners..."
          echo "Reason: ${{ github.event.inputs.reason }}"
          
          # Since we're running ON a k8s-runner, we have kubectl access
          kubectl delete pods -n arc-systems-rust-builder \
            -l runner-deployment-name=org-runners-rust-builder \
            --force --grace-period=30 || echo "No pods found or unable to delete"
          
          echo "✅ Runner pods deleted. Arc will recreate them with latest image."
          echo "Note: New runners will pull ghcr.io/5dlabs/agent-platform/rust-builder:latest"